name: Ping Supabase and Render Site

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch: 

jobs:
  ping-database-and-site:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Ping Supabase
        env:
          SUPABASE_URL_DB: ${{ secrets.SUPABASE_URL_DB }}
          SUPABASE_ANON_KEY_DB: ${{ secrets.SUPABASE_ANON_KEY_DB }}
        run: python scripts/ping_supabase.py

      - name: Keep Render Site Active
        env:
          RENDER_SITE_URL: ${{ secrets.RENDER_SITE_URL }}
        run: python scripts/ping_render_site.py
